name: Go Test

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Go Test
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test ./... -v -coverpkg=./...  -coverprofile=coverage.out
